# Generated by Django 5.2.17 on 2026-09-20 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inmuebles', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCoarrendatario', models.IntegerField(blank=True)),
                ('idsDependientes', models.JSONField(blank=True, default=list)),
                ('idsReferencias', models.JSONField(blank=True, default=list)),
                ('idDeclaracionIngresos', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('contratada', 'Contratada')], default='pendiente', max_length=20)),
                ('solicitudAtendida', models.BooleanField(default=False)),
                ('solicitudContratada', models.BooleanField(default=False)),
                ('solicitudRevisada', models.BooleanField(default=False)),
                ('comentario_estado', models.CharField(blank=True, max_length=200, null=True)),
                ('duracionContrato', models.IntegerField(default=6)),
                ('seguroArrendamiento', models.BooleanField(blank=True, null=True)),
                ('depositoVoluntario', models.BooleanField(blank=True, null=True)),
                ('valorDepositoVoluntario', models.CharField(blank=True, max_length=10, null=True)),
                ('otraGarantiaAcrodada', models.BooleanField(blank=True, null=True)),
                ('especificacionOtraGarantiaAcordada', models.CharField(blank=True, max_length=200, null=True)),
                ('mascotas', models.BooleanField(default=False)),
                ('numMascotas', models.IntegerField(blank=True, null=True)),
                ('tipoMascotas', models.CharField(blank=True, null=True)),
                ('cedulaArrendatario', models.FileField(blank=True, null=True, upload_to='media/cedulas/')),
                ('cedulaCodeudor', models.FileField(blank=True, null=True, upload_to='media/cedulas/')),
                ('cedulasHabitantes', models.FileField(blank=True, null=True, upload_to='media/cedulas/habitantes/')),
                ('aceptaTratamientodeDatos', models.BooleanField(default=False)),
                ('certificado_laboral_arrendatario', models.FileField(blank=True, null=True, upload_to='media/laborales/')),
                ('certificado_laboral_codeudor', models.FileField(blank=True, null=True, upload_to='media/laborales/')),
                ('desprendible_nomina_arrendatario', models.FileField(blank=True, null=True, upload_to='media/nominas/')),
                ('desprendible_nomina_codeudor', models.FileField(blank=True, null=True, upload_to='media/nominas/')),
                ('declaracion_renta_arrendatario', models.FileField(blank=True, null=True, upload_to='media/renta/')),
                ('declaracion_renta_codeudor', models.FileField(blank=True, null=True, upload_to='media/renta/')),
                ('camara_comercio_arrendatario', models.FileField(blank=True, null=True, upload_to='media/comercio/')),
                ('camara_comercio_codeudor', models.FileField(blank=True, null=True, upload_to='media/comercio/')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='inmuebles.arrendar')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='usuarios.arrendatario')),
            ],
            options={
                'unique_together': {('casa', 'usuario')},
            },
        ),
    ]
