# Generated by Django 6.0.3 on 2026-09-20 22:21

import inmobiliarias.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='camara_comercio_arrendatario',
            field=models.FileField(blank=True, null=True, storage=inmobiliarias.storage.private_media_storage, upload_to='media/comercio/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='camara_comercio_codeudor',
            field=models.FileField(blank=True, null=True, storage=inmobiliarias.storage.private_media_storage, upload_to='media/comercio/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cedulaArrendatario',
            field=models.FileField(blank=True, null=True, storage=inmobiliarias.storage.private_media_storage, upload_to='media/cedulas/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cedulaCodeudor',
            field=models.FileField(blank=True, null=True, storage=inmobiliarias.storage.private_media_storage, upload_to='media/cedulas/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='cedulasHabitantes',
            field=models.FileField(blank=True, null=True, storage=inmobiliarias.storage.private_media_storage, upload_to='media/cedulas/habitantes/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='certificado_laboral_arrendatario',
            field=models.FileField(blank=True, null=True, storage=inmobiliarias.storage.private_media_storage, upload_to='media/laborales/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='certificado_laboral_codeudor',
            field=models.FileField(blank=True, null=True, storage=inmobiliarias.storage.private_media_storage, upload_to='media/laborales/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='declaracion_renta_arrendatario',
            field=models.FileField(blank=True, null=True, storage=inmobiliarias.storage.private_media_storage, upload_to='media/renta/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='declaracion_renta_codeudor',
            field=models.FileField(blank=True, null=True, storage=inmobiliarias.storage.private_media_storage, upload_to='media/renta/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='desprendible_nomina_arrendatario',
            field=models.FileField(blank=True, null=True, storage=inmobiliarias.storage.private_media_storage, upload_to='media/nominas/'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='desprendible_nomina_codeudor',
            field=models.FileField(blank=True, null=True, storage=inmobiliarias.storage.private_media_storage, upload_to='media/nominas/'),
        ),
    ]
