# Generated by Django 6.0.3 on 2026-09-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_almacenamiento_privado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='idCoarrendatario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
