# Generated by Django 5.2.17 on 2026-09-20 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coarrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_documento', models.CharField(blank=True, choices=[('CC', 'Cédula'), ('CE', 'Cédula de extranjería'), ('RC', 'Registro civil'), ('TI', 'Tarjeta de identidad'), ('DNI', 'Documento de identificación nacional')], max_length=3, null=True)),
                ('doc_identificacion', models.IntegerField(blank=True, null=True)),
                ('lugarExpCedula', models.CharField(blank=True, max_length=255)),
                ('parentezco', models.CharField(blank=True, max_length=30, null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('barrio', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=255)),
                ('empresa', models.CharField(blank=True, max_length=255)),
                ('ocupacion', models.CharField(blank=True, max_length=255)),
                ('ingresosMensualesTotales', models.CharField(blank=True, max_length=15)),
                ('declaraRenta', models.BooleanField(default=False)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('direccionCorrespondencia', models.CharField(blank=True, max_length=255)),
                ('barrioCorrespondencia', models.CharField(blank=True, max_length=255)),
                ('ciudadCorrespondencia', models.CharField(blank=True, max_length=255)),
                ('celularDos', models.IntegerField(blank=True, null=True)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.arrendatario')),
            ],
            options={
                'verbose_name': 'Coarrendatario',
            },
        ),
        migrations.CreateModel(
            name='declaracion_ingresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoContrato', models.CharField(blank=True, max_length=255, null=True)),
                ('jefeInmediato', models.CharField(blank=True, max_length=255, null=True)),
                ('tiempoLaboral', models.CharField(blank=True, max_length=255, null=True)),
                ('salarioBasicoMensual', models.CharField(blank=True, max_length=255, null=True)),
                ('otrosIngresos', models.CharField(blank=True, max_length=255, null=True)),
                ('telefonoEmpresa', models.CharField(blank=True, max_length=12, null=True)),
                ('direccion_laboral', models.CharField(blank=True, max_length=100, null=True)),
                ('declaraRenta', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.arrendatario')),
            ],
            options={
                'verbose_name': 'Declaración de ingresos arrendatario',
                'verbose_name_plural': 'Declaraciones de ingresos arrendatario',
            },
        ),
        migrations.CreateModel(
            name='dependientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('tipo_documento', models.CharField(blank=True, choices=[('CC', 'Cédula'), ('CE', 'Cédula de extranjería'), ('RC', 'Registro civil'), ('TI', 'Tarjeta de identidad'), ('DNI', 'Documento de identificación nacional')], max_length=3, null=True)),
                ('doc_identificacion', models.PositiveBigIntegerField(blank=True, null=True)),
                ('lugarExpCedula', models.CharField(blank=True, max_length=255, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=30, null=True)),
                ('parentezco', models.CharField(blank=True, max_length=30, null=True)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.arrendatario')),
            ],
            options={
                'verbose_name': 'Personas dependientes del arrendatario',
                'verbose_name_plural': 'Personas dependientes del arrendatario',
            },
        ),
        migrations.CreateModel(
            name='referencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('parentezco', models.CharField(blank=True, max_length=30, null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('dir_residencia', models.CharField(blank=True, max_length=50, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=30, null=True)),
                ('motivoRetiro', models.CharField(blank=True, max_length=50, null=True)),
                ('refArrendadorAnterior', models.BooleanField(default=False)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.arrendatario')),
            ],
            options={
                'verbose_name': 'Referencia del arrendatario',
                'verbose_name_plural': 'Referencias del arrendatario',
            },
        ),
    ]
