# Generated by Django 6.0.3 on 2026-09-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendatarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coarrendatario',
            name='celular',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coarrendatario',
            name='celularDos',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coarrendatario',
            name='doc_identificacion',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referencias',
            name='celular',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
