# Generated by Django 5.2.17 on 2026-09-20 17:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, choices=[('CC', 'Cédula'), ('CE', 'Cédula de extranjería'), ('RC', 'Registro civil'), ('TI', 'Tarjeta de identidad'), ('DNI', 'Documento de identificación nacional')], max_length=3, null=True)),
                ('doc_identificacion', models.IntegerField(blank=True, null=True)),
                ('lugarExpCedula', models.CharField(blank=True, max_length=255)),
                ('CodClasificaIndustrialIU', models.IntegerField(blank=True, null=True)),
                ('descActividadEconomica', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('direccion', models.CharField(max_length=255)),
                ('barrio', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=255, null=True)),
                ('direccionCorrespondencia', models.CharField(blank=True, max_length=255, null=True)),
                ('barrioCorrespondencia', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudadCorrespondencia', models.CharField(blank=True, max_length=255, null=True)),
                ('celular', models.PositiveBigIntegerField(blank=True, null=True)),
                ('celularDos', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cuentaDaviplata', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cuentaNequi', models.PositiveBigIntegerField(blank=True, null=True)),
                ('llave', models.CharField(blank=True, max_length=40, null=True)),
                ('CuentaBancolombia', models.PositiveBigIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrador de aplicación',
                'verbose_name_plural': 'Administradores de la aplicación',
            },
        ),
        migrations.CreateModel(
            name='arrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, choices=[('CC', 'Cédula'), ('CE', 'Cédula de extranjería'), ('RC', 'Registro civil'), ('TI', 'Tarjeta de identidad'), ('DNI', 'Documento de identificación nacional')], max_length=3, null=True)),
                ('doc_identificacion', models.IntegerField(blank=True, null=True)),
                ('lugarExpCedula', models.CharField(blank=True, max_length=255, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=255, null=True)),
                ('estadoCivil', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('CodClasificaIndustrialIU', models.IntegerField(blank=True, null=True)),
                ('descActividadEconomica', models.CharField(blank=True, max_length=255, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('barrio', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=255, null=True)),
                ('direccionCorrespondencia', models.CharField(blank=True, max_length=255)),
                ('barrioCorrespondencia', models.CharField(blank=True, max_length=255)),
                ('ciudadCorrespondencia', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('arrendatarioAprobado', models.BooleanField(default=False)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('celularDos', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arrendatario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arrendatario',
                'verbose_name_plural': 'Arrendatarios',
            },
        ),
        migrations.CreateModel(
            name='propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, choices=[('CC', 'Cédula'), ('CE', 'Cédula de extranjería'), ('RC', 'Registro civil'), ('TI', 'Tarjeta de identidad'), ('DNI', 'Documento de identificación nacional')], max_length=3, null=True)),
                ('doc_identificacion', models.IntegerField(blank=True, null=True)),
                ('lugarExpCedula', models.CharField(blank=True, max_length=255, null=True)),
                ('descActividadEconomica', models.CharField(blank=True, max_length=255, null=True)),
                ('CodClasificaIndustrialIU', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('barrio', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=255, null=True)),
                ('direccionCorrespondencia', models.CharField(blank=True, max_length=255, null=True)),
                ('barrioCorrespondencia', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudadCorrespondencia', models.CharField(blank=True, max_length=255, null=True)),
                ('celular', models.PositiveBigIntegerField(blank=True, null=True)),
                ('celularDos', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cuentaDaviplata', models.PositiveBigIntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cuentaNequi', models.PositiveBigIntegerField(blank=True, null=True)),
                ('llave', models.CharField(blank=True, max_length=40, null=True)),
                ('CuentaBancolombia', models.PositiveBigIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propietario de casa',
                'verbose_name_plural': 'Propietarios de casas',
            },
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, choices=[('CC', 'Cédula'), ('CE', 'Cédula de extranjería'), ('RC', 'Registro civil'), ('TI', 'Tarjeta de identidad'), ('DNI', 'Documento de identificación nacional')], max_length=3, null=True)),
                ('doc_identificacion', models.IntegerField(blank=True, null=True)),
                ('lugarExpCedula', models.CharField(blank=True, max_length=255, null=True)),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('barrio', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=255, null=True)),
                ('direccionCorrespondencia', models.CharField(blank=True, max_length=255)),
                ('barrioCorrespondencia', models.CharField(blank=True, max_length=255)),
                ('ciudadCorrespondencia', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('celularDos', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
