# Generated by Django 6.0.3 on 2026-03-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='arrendatarioAprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propietario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
