# Generated by Django 6.0.3 on 2026-03-20 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_proveedor_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='Activo',
            new_name='activo',
        ),
    ]
