# Generated by Django 6.0.3 on 2026-03-20 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_activo_administrador_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='activo',
            new_name='Activo',
        ),
    ]
