# Generated by Django 6.0.3 on 2026-03-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_activo_administrador_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='Activo',
            new_name='activo',
        ),
        migrations.RemoveField(
            model_name='declaracion_ingresos',
            name='celular_empresa',
        ),
        migrations.RemoveField(
            model_name='declaracion_ingresos',
            name='entidad_labora',
        ),
        migrations.RemoveField(
            model_name='declaracion_ingresos',
            name='jefe_inmediato',
        ),
        migrations.RemoveField(
            model_name='declaracion_ingresos',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='declaracion_ingresos',
            name='ocupacion',
        ),
        migrations.RemoveField(
            model_name='dependientes',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='dependientes',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='referencias',
            name='barrio',
        ),
        migrations.RemoveField(
            model_name='referencias',
            name='empresa',
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='estadoCivil',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coarrendatario',
            name='declaraRenta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coarrendatario',
            name='ingresosMensualesTotales',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='coarrendatario',
            name='parentezco',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='declaracion_ingresos',
            name='declaraRenta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='declaracion_ingresos',
            name='jefeInmediato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='declaracion_ingresos',
            name='otrosIngresos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='declaracion_ingresos',
            name='salarioBasicoMensual',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='declaracion_ingresos',
            name='telefonoEmpresa',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='declaracion_ingresos',
            name='tiempoLaboral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='declaracion_ingresos',
            name='tipoContrato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='referencias',
            name='motivoRetiro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='referencias',
            name='refArrendadorAnterior',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='referencias',
            name='dir_residencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
