# Generated by Django 6.0.3 on 2026-03-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_rename_activo_administrador_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coarrendatario',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
