# Generated by Django 6.0.3 on 2026-04-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_coarrendatario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='llave',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='llave',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
