# Generated by Django 6.0.3 on 2026-03-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clausula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='contra_local_vivenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechainicio', models.DateField(blank=True, default='2024-01-01')),
                ('fechafin', models.DateField(blank=True, default='2024-01-01')),
                ('diaHInicioPago', models.IntegerField(blank=True, null=True)),
                ('diaFinPago', models.IntegerField(blank=True, null=True)),
                ('contrato_Activo', models.BooleanField(default=False)),
                ('ciudad', models.CharField(max_length=30)),
                ('tipoContrato', models.CharField(blank=True, max_length=30)),
                ('fechaEntregaInmueble', models.DateField(blank=True, default='2024-01-01')),
                ('fechaRestitucionInmueble', models.DateField(blank=True, default='2024-01-01')),
                ('fecha', models.DateField(blank=True)),
                ('estaFirmado', models.BooleanField(default=False)),
                ('estaFirmadoArrendatario', models.BooleanField(default=False)),
                ('pdf_firmado', models.FileField(blank=True, null=True, upload_to='contratos_firmados/')),
                ('pdf_inventario', models.FileField(blank=True, null=True, upload_to='contratos/inventarios/')),
                ('numOtrosi', models.IntegerField(default=0)),
                ('otrosiGenerado', models.BooleanField(default=False)),
                ('fechafinOtrosi', models.DateField(blank=True, default='2024-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoOtroSi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmaElectronicaArrendador', models.BooleanField(default=False)),
                ('firmaElectronicaArrendatario', models.BooleanField(default=False)),
                ('otroSi_firmado', models.FileField(blank=True, null=True, upload_to='otroSi_firmados/')),
            ],
        ),
        migrations.CreateModel(
            name='fechadePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechadePago', models.IntegerField(blank=True, null=True)),
                ('diasAtrasado', models.IntegerField(blank=True, null=True)),
                ('diasAdelantado', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FechaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('fechadeMesaPagar', models.DateField(blank=True, null=True)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REALIZADO', 'Realizado')], default='PENDIENTE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='imagenReporteNovedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='otroSi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonmensualOtrosi', models.IntegerField(blank=True, null=True)),
                ('fechainicio', models.DateField(blank=True, default='2024-01-01')),
                ('fechafin', models.DateField(blank=True, default='2024-01-01')),
                ('aceptaOtroSi', models.BooleanField(default=False)),
                ('aceptaOtroSiArrendatario', models.BooleanField(default=False)),
                ('vistaImpresion', models.BooleanField(default=False)),
                ('numOtrosi', models.IntegerField(default=0)),
                ('pdf_firmado', models.FileField(blank=True, null=True, upload_to='otrosi_firmados/')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteInconformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estaInconforme', models.BooleanField(default=False)),
                ('inconformidadSolucionada', models.BooleanField(default=False)),
                ('Inconformidad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='reporteNovedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReporte', models.DateTimeField(auto_now_add=True, null=True)),
                ('texto', models.TextField()),
                ('textoAdministrador', models.TextField(blank=True, null=True)),
                ('estaHabilitado', models.BooleanField(default=False)),
                ('estaResuelto', models.BooleanField(default=False)),
                ('estaResueltoArrendatario', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReportePagoRecibos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenReciboLuz', models.ImageField(upload_to='recibos/')),
                ('imagenReciboAgua', models.ImageField(upload_to='recibos/')),
                ('imagenReciboGas', models.ImageField(upload_to='recibos/')),
                ('imagenReciboBioagricola', models.ImageField(upload_to='recibos/')),
            ],
        ),
        migrations.CreateModel(
            name='videoReporteNovedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_archivo', models.FileField(upload_to='media/')),
            ],
        ),
    ]
