# Generated by Django 6.0.3 on 2026-09-20 22:21

import inmobiliarias.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato_local_vivienda',
            name='pdf_firmado',
            field=models.FileField(blank=True, null=True, storage=inmobiliarias.storage.private_media_storage, upload_to='contratos_firmados/'),
        ),
        migrations.AlterField(
            model_name='contrato_local_vivienda',
            name='pdf_inventario',
            field=models.FileField(blank=True, null=True, storage=inmobiliarias.storage.private_media_storage, upload_to='contratos/inventarios/'),
        ),
        migrations.AlterField(
            model_name='contratootrosi',
            name='otroSi_firmado',
            field=models.FileField(blank=True, null=True, storage=inmobiliarias.storage.private_media_storage, upload_to='otroSi_firmados/'),
        ),
        migrations.AlterField(
            model_name='imagenreportenovedades',
            name='imagen',
            field=models.ImageField(storage=inmobiliarias.storage.private_media_storage, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='otrosi',
            name='pdf_firmado',
            field=models.FileField(blank=True, null=True, storage=inmobiliarias.storage.private_media_storage, upload_to='otrosi_firmados/'),
        ),
        migrations.AlterField(
            model_name='reportepagorecibos',
            name='imagenReciboAgua',
            field=models.ImageField(storage=inmobiliarias.storage.private_media_storage, upload_to='recibos/'),
        ),
        migrations.AlterField(
            model_name='reportepagorecibos',
            name='imagenReciboBioagricola',
            field=models.ImageField(storage=inmobiliarias.storage.private_media_storage, upload_to='recibos/'),
        ),
        migrations.AlterField(
            model_name='reportepagorecibos',
            name='imagenReciboGas',
            field=models.ImageField(storage=inmobiliarias.storage.private_media_storage, upload_to='recibos/'),
        ),
        migrations.AlterField(
            model_name='reportepagorecibos',
            name='imagenReciboLuz',
            field=models.ImageField(storage=inmobiliarias.storage.private_media_storage, upload_to='recibos/'),
        ),
        migrations.AlterField(
            model_name='videoreportenovedades',
            name='video_archivo',
            field=models.FileField(storage=inmobiliarias.storage.private_media_storage, upload_to='media/'),
        ),
    ]
