# Generated by Django 6.0.3 on 2026-03-19 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('inicio', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contra_local_vivenda',
            name='coarrendatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.coarrendatario'),
        ),
        migrations.AddField(
            model_name='contra_local_vivenda',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.arrendar'),
        ),
        migrations.AddField(
            model_name='contra_local_vivenda',
            name='userAdministrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.administrador'),
        ),
        migrations.AddField(
            model_name='contra_local_vivenda',
            name='userArrendatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.arrendatario'),
        ),
        migrations.AddField(
            model_name='clausula',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clausulas', to='contratos.contra_local_vivenda'),
        ),
        migrations.AddField(
            model_name='contratootrosi',
            name='Contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.contra_local_vivenda'),
        ),
        migrations.AddField(
            model_name='fechadepago',
            name='contratoNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.contra_local_vivenda'),
        ),
        migrations.AddField(
            model_name='fechapago',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas_pago', to='contratos.contra_local_vivenda'),
        ),
        migrations.AddField(
            model_name='otrosi',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otroSI', to='contratos.contra_local_vivenda'),
        ),
        migrations.AddField(
            model_name='reporteinconformidad',
            name='reporteinconformidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.contra_local_vivenda'),
        ),
        migrations.AddField(
            model_name='reportenovedades',
            name='contratoNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contratos.contra_local_vivenda'),
        ),
        migrations.AddField(
            model_name='imagenreportenovedades',
            name='reporteNovedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='contratos.reportenovedades'),
        ),
        migrations.AddField(
            model_name='reportepagorecibos',
            name='reportePagoReciboContrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_recibos', to='contratos.contra_local_vivenda'),
        ),
        migrations.AddField(
            model_name='videoreportenovedades',
            name='reporteNovedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='contratos.reportenovedades'),
        ),
    ]
