# Generated by Django 6.0.3 on 2026-09-27 22:27

import django.db.models.deletion
import inmobiliarias.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_almacenamiento_privado'),
    ]

    operations = [
        migrations.CreateModel(
            name='audioReporteNovedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_archivo', models.FileField(storage=inmobiliarias.storage.private_media_storage, upload_to='media/')),
                ('reporteNovedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='contratos.reportenovedades')),
            ],
        ),
    ]
