# Generated by Django 6.0.3 on 2026-03-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='arrendar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoInmueble', models.CharField(blank=True, max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('barrio', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(max_length=100)),
                ('condiciones', models.TextField(blank=True, max_length=100, null=True)),
                ('con_administracion', models.BooleanField(default=False)),
                ('fotoPrincipal', models.ImageField(null=True, upload_to='media/')),
                ('publicar', models.BooleanField(default=False)),
                ('conCodeudor', models.BooleanField(default=True)),
                ('arrendada', models.BooleanField(default=False)),
                ('canonmensual', models.IntegerField()),
                ('observacion_canonmensual', models.TextField(blank=True)),
                ('deposito', models.IntegerField()),
                ('observacion_deposito', models.TextField(blank=True)),
                ('sala', models.BooleanField(default=False)),
                ('observacion_sala', models.TextField(blank=True)),
                ('comedor', models.BooleanField(default=False)),
                ('observacion_comedor', models.TextField(blank=True)),
                ('cocina', models.BooleanField(default=False)),
                ('observacion_cocina', models.TextField(blank=True)),
                ('habitaciones', models.BooleanField(default=False)),
                ('observacion_habitaciones', models.TextField(blank=True)),
                ('baños', models.BooleanField(default=False)),
                ('observacion_baños', models.TextField(blank=True)),
                ('patio', models.BooleanField(default=False)),
                ('observacion_patio', models.TextField(blank=True)),
                ('garage', models.BooleanField(default=False)),
                ('observacion_garage', models.TextField(blank=True)),
                ('tanquesubterraneo', models.BooleanField(default=False)),
                ('observacion_tanquesubterraneo', models.TextField(blank=True)),
                ('ser_agua', models.BooleanField(default=False)),
                ('observacion_ser_agua', models.TextField(blank=True)),
                ('ser_energia', models.BooleanField(default=False)),
                ('observacion_ser_energia', models.TextField(blank=True)),
                ('ser_gas_domiciliario', models.BooleanField(default=False)),
                ('observacion_ser_gas_domiciliario', models.TextField(blank=True)),
                ('ser_bioagricola', models.BooleanField(default=False)),
                ('observacion_ser_bioagricola', models.TextField(blank=True)),
                ('otros', models.TextField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Casa registrada para arrendar',
                'verbose_name_plural': 'Casas registradas para arrendar',
            },
        ),
        migrations.CreateModel(
            name='arriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud_form_orig', models.BooleanField(default=False)),
                ('Inventario', models.BooleanField(default=False)),
                ('Registro_fotografico', models.BooleanField(default=False)),
                ('Visita_verificacion', models.BooleanField(default=False)),
                ('Verificacion_pagos_servicios', models.BooleanField(default=False)),
                ('Notificacion_renova_cancela', models.BooleanField(default=False)),
                ('Documentos_ident_arrendatario', models.BooleanField(default=False)),
                ('firma_letras', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Informacion de arriendos en curso',
                'verbose_name_plural': 'Informacion de arriendos en curso',
            },
        ),
        migrations.CreateModel(
            name='Imagen_casa_arrendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='casa/imagenes')),
            ],
            options={
                'verbose_name': 'Mas fotos de las casas registradas',
                'verbose_name_plural': 'Mas fotos de las casas registradas',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Video_Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('video_archivo', models.FileField(upload_to='casa/videos')),
            ],
        ),
    ]
