# Generated by Django 6.0.3 on 2026-03-19 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inicio', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendar',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.propietario'),
        ),
        migrations.AddField(
            model_name='arriendo',
            name='arrendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.arrendar'),
        ),
        migrations.AddField(
            model_name='imagen_casa_arrendar',
            name='arrendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.arrendar'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='inicio.arrendar'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='usuarios.arrendatario'),
        ),
        migrations.AddField(
            model_name='video_casa',
            name='arrendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.arrendar'),
        ),
        migrations.AlterUniqueTogether(
            name='solicitud',
            unique_together={('casa', 'usuario')},
        ),
    ]
