# Generated by Django 6.0.3 on 2026-03-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendar',
            name='usoInmueble',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='camara_comercio_arrendatario',
            field=models.FileField(blank=True, null=True, upload_to='media/comercio/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='camara_comercio_codeudor',
            field=models.FileField(blank=True, null=True, upload_to='media/comercio/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cedulaArrendatario',
            field=models.FileField(blank=True, null=True, upload_to='media/cedulas/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cedulaCodeudor',
            field=models.FileField(blank=True, null=True, upload_to='media/cedulas/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='cedulasHabitantes',
            field=models.FileField(blank=True, null=True, upload_to='media/cedulas/habitantes/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='certificado_laboral_arrendatario',
            field=models.FileField(blank=True, null=True, upload_to='media/laborales/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='certificado_laboral_codeudor',
            field=models.FileField(blank=True, null=True, upload_to='media/laborales/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='declaracion_renta_arrendatario',
            field=models.FileField(blank=True, null=True, upload_to='media/renta/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='declaracion_renta_codeudor',
            field=models.FileField(blank=True, null=True, upload_to='media/renta/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='depositoVoluntario',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='desprendible_nomina_arrendatario',
            field=models.FileField(blank=True, null=True, upload_to='media/nominas/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='desprendible_nomina_codeudor',
            field=models.FileField(blank=True, null=True, upload_to='media/nominas/'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='duracionContrato',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='especificacionOtraGarantiaAcordada',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='mascotas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='numMascotas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='otraGarantiaAcrodada',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='seguroArrendamiento',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipoMascotas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='valorDepositoVoluntario',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='imagen_casa_arrendar',
            name='imagen',
            field=models.ImageField(upload_to='media/casa/imagenes'),
        ),
    ]
