# Generated by Django 6.0.3 on 2026-03-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_arrendar_usoinmueble_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='aceptaTratamientodeDatos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='mascotas',
            field=models.BooleanField(default=False),
        ),
    ]
