# Generated by Django 6.0.3 on 2026-03-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_solicitud_aceptatratamientodedatos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='tipoMascotas',
            field=models.CharField(blank=True, null=True),
        ),
    ]
