# Generated by Django 6.0.3 on 2026-04-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_solicitud_tipomascotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='comentarioEstado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
    ]
