# Generated by Django 6.0.3 on 2026-04-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_solicitud_comentarioestado_alter_solicitud_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='comentarioEstado',
            new_name='comentario_estado',
        ),
    ]
