# Generated by Django 6.0.3 on 2026-04-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_rename_comentarioestado_solicitud_comentario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='solicitudAtendida',
            field=models.BooleanField(default=False),
        ),
    ]
