# Generated by Django 6.0.3 on 2026-04-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_solicitud_solicitudatendida'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='solicitudContratada',
            field=models.BooleanField(default=False),
        ),
    ]
