# Generated by Django 6.0.3 on 2026-04-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_solicitud_solicitudcontratada'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrendar',
            name='matriculaInmobiliaria',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
