# Generated by Django 6.0.3 on 2026-04-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_arrendar_matriculainmobiliaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrendar',
            name='condiciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arrendar',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
