# Generated by Django 5.2.17 on 2026-09-20 17:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratos', '0001_initial'),
        ('inmuebles', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cualidad de proveedor',
                'verbose_name_plural': 'Cualidades de proveedor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(help_text='De 1 (muy mala) a 5 (excelente).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, max_length=500)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('atributos', models.ManyToManyField(blank=True, related_name='calificaciones', to='calificaciones.atributoproveedor')),
                ('casa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_proveedor', to='inmuebles.arrendar')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_a_proveedores', to='usuarios.propietario')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='usuarios.proveedor')),
            ],
            options={
                'verbose_name': 'Calificación del proveedor',
                'verbose_name_plural': 'Calificaciones del proveedor',
                'ordering': ['-creada'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CalificacionArrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(help_text='De 1 (muy mala) a 5 (excelente).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, max_length=500)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='usuarios.arrendatario')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones_arrendatario', to='contratos.contrato_local_vivienda')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_a_arrendatarios', to='usuarios.propietario')),
            ],
            options={
                'verbose_name': 'Calificación del arrendatario',
                'verbose_name_plural': 'Calificaciones del arrendatario',
                'ordering': ['-creada'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('propietario', 'arrendatario', 'contrato'), name='calificacion_arrendatario_unica_por_contrato')],
            },
        ),
    ]
